directories:
  output: dist-app-v6
  buildResources: build
appId: com.obamaxgardens.management
productName: Obamax Gardens
copyright: Copyright 2025 Obamax Gardens Ltd
files:
  - filter:
      - electron/**/*
      - public/logo.jpg
      - public/logo.png
      - '!node_modules/**/*'
      - '!resources/**/*'
      - '!public/build/**/*'
extraResources: []
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
  icon: public/logo.png
  requestedExecutionLevel: asInvoker
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  allowElevation: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Obamax Gardens
  deleteAppDataOnUninstall: false
  differentialPackage: false
electronVersion: 34.5.8
